# services:
#   - type: web
#     name: indiamart-scraper
#     env: node
#     buildCommand: npm install && node node_modules/puppeteer/install.js && npx puppeteer browser install chrome
#     startCommand: node server.js
#     envVars:
#       - key: MONGODB_URI
#         sync: false
#       - key: PORT
#         value: 10000


# services:
#   - type: web
#     name: scraper-app
#     env: node
#     plan: free
#     branch: main


#     # buildCommand: |
#     #   sudo apt-get update
#     #   sudo apt-get install -y wget gnupg
#     #   wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
#     #   sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
#     #   sudo apt-get update
#     #   sudo apt-get install -y google-chrome-stable
#     startCommand: node server.js
#     envVars:
#       - key: MONGODB_URI
#         sync: false
#       - key: PORT
#         value: 10000
#       - key: PUPPETEER_EXECUTABLE_PATH
#         value: /usr/bin/google-chrome-stable








services:
  - type: web
    name: scraper-app
    env: node
    plan: free
    branch: main
    buildCommand: |
      npm install
    startCommand: node server.js